### ISSUE TITLE
duplicate song detected but not really

### ISSUE THREAD

**Issue by mockuser404** [Footsiefat/zspotify#137]
Look at these two songs by same artist, they are both the same songs but one is Explicit and features some other artist and the other is not explicit and has some different lyrics (replacing swears)

This library detects them as the same song and downloads only the first encountered one (this is technically right)

This is a very special edge case but a valid bug nevertheless.

https://open.spotify.com/track/7qVjoGvjdOFfk3uKVhvZU9
https://open.spotify.com/track/3aEcaegTsg7rnU0Mk5a7Eu

**Comment by yiannisha** [comment]
I am currently working on this and I will probably have a PR ready in about an hour.

**Comment by yiannisha** [comment]
Just made PR #174

**Comment by logykk** [comment]
PR #174 is in.
