### ISSUE TITLE
Keep a list of all downloaded songs across folders?

### ISSUE THREAD

**Issue by Vinnpinn** [Footsiefat/zspotify#161]
Is there currently a way to keep track of alle the already downloaded songs if you move them from their download location or if they're in multiple playlists?
This would avoid downloading the same files over and over again and would also allow me to move the files to another machine. This would also make it a lot easier to handle dynamic playlists like the mixtapes. 

From what I've seen it's currently only possible to detect duplicates that are in the same download folder.

**Comment by Equim-chan** [comment]
FYI this is similar to youtube-dl's `--download-archive` option.

**Comment by yiannisha** [comment]
Hello, I'll start working on this today.

**Comment by yiannisha** [comment]
Hey I just made PR #186 that addresses this feature.

**Comment by yiannisha** [comment]
@logykk We should close this one.

**Comment by Vinnpinn** [comment]
Fixen in #186
