### ISSUE TITLE
Feature Idea:

### ISSUE THREAD

**Issue by Ego-Matthisum** [Footsiefat/zspotify#172]
Ability to add a .txt file with links to several artists/playlists/whatever as an argument to automatically download everything specified.

**Comment by AnotherAsian123** [comment]
Seconded, would make backing up my playlists so much easier. Just copying all their links to txt, running zspotify every couple of days or so to update my offline library.

**Comment by el-gringo-alto** [comment]
I can start working on this

**Comment by PhlegethonAcheron** [comment]
This is already possible through the use of shell scripts
Here's the batch script I wrote and am using:
`for /F "tokens=*" %%A in (C:\Users\Acheron\Zspotify\Playlists.txt) do python zspotify %%A`
