### ISSUE TITLE
DOWNLOAD_REAL_TIME results in download speeds that are 3-4x slower than real time

### ISSUE THREAD

**Issue by dig65** [Footsiefat/zspotify#175]
Setting DOWNLOAD_REAL_TIME to true in the config file results in download speeds that are 3-4x slower than real time. I.E., a 3 minute song takes 9-12 minutes to download.

As of c5f4bf1, still happening.

**Comment by CyberLykan** [comment]
Can confirm there's an issue. Seems to be downloading at around 10kbps for me.

**Comment by anindianforor** [comment]
Observed the same..

**Comment by breaddevil** [comment]
The current formula for the pause is duration_ms / ZSpotify.CONFIG.get_chunk_size()

https://github.com/Footsiefat/zspotify/blob/45f276013f58b85ad9128cc78d42e6d5d9b0da97/zspotify/track.py#L144

I believe a more appropriate one would be duration / number of chunks (in seconds), or
`pause = duration_ms / total_size * ZSpotify.CONFIG.get_chunk_size() / 1000`.
