### ISSUE TITLE
Songs are not downloading as expected 

### ISSUE THREAD

**Issue by sanalsunny** [Footsiefat/zspotify#177]
Songs are not fully downloaded. see the screenshot 

![image](https://user-images.githubusercontent.com/83308684/139727536-8a781525-72b4-4f4c-8c60-a4ea92f87e23.png)

so here most of the songs stoped processing midway

**Comment by JamesKai** [comment]
This is the exact same issue as #162

**Comment by logykk** [comment]
Duplicate of #162, move discussion over there.
