### ISSUE TITLE
Downloading albums has an issue when getting the full track data.

### ISSUE THREAD

**Issue by JemPH** [Footsiefat/zspotify#180]
![image](https://user-images.githubusercontent.com/46235805/139961373-b4727d1b-9c75-4719-8eae-222cc8a06bca.png)
![image](https://user-images.githubusercontent.com/46235805/139961549-dbc5a587-4769-4c7c-85e9-ad70501e1547.png)

When downloading an album, I encounter some problems. I am unable to get the full data for some tracks in the album.

**Comment by logykk** [comment]
That's all the metadata available from Spotify. Genre, rating and composer aren't supplied.
