### ISSUE TITLE
When I launch the program it says this

### ISSUE THREAD

**Issue by rcop98** [Footsiefat/zspotify#185]
C:\Users\Rafmandudebro\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by Footsiefat** [comment]
It means exactly what its saying. It requires ffmpeg to be installed as is said on the readme :P

**Comment by rcop98** [comment]
I installed that

**Comment by Touexe** [comment]
@rcop98 did u add ffmpeg to PATH?

**Comment by rcop98** [comment]
I also did that yeah.

**Comment by Touexe** [comment]
@rcop98 it's an issue with pydub library.... you might need to open issue in pydub repo instead

**Comment by rcop98** [comment]
Will do, thanks for letting me know and also your time

**Comment by alexdoub** [comment]
When you type `ffmpeg` into your terminal, what happens?

**Comment by rcop98** [comment]
Ey just to let anyone know this is no longer an issue for me. I ended up forgetting to open up an issue in the Pydub library. I did end up re installing both the FFmpeg stuff, and also zspotify itself a few times. Initially it didn't fix the issue, but after a few times it did. I'm not quite sure exactly what I did or didn't do fix it, but yeah.
