### ISSUE TITLE
Attempting to download a playlist and specifying #-## results in 2 "2 positional argument" exception.

### ISSUE THREAD

**Issue by metalphoenix** [Footsiefat/zspotify#188]
![image](https://user-images.githubusercontent.com/6956650/141221140-331b797b-0e75-4295-8b57-42dfbf4ca62c.png)

In my example, I'm specifying "2-87" (because the application can't seem to download anything except the first playlist in the list which is, I suspect another issue). 

As you can see in the screenshot, you have at least an "off by one" error since I entered 2-87 and output said "Downloading 2 to 88".

**Comment by logykk** [comment]
That seems to be quite an old version of zspotify. This does not occur in the newest version of the code.

**Comment by metalphoenix** [comment]
That's your latest version, 2.4.1, _released 15 days ago._ Quite old?

https://github.com/Footsiefat/zspotify/releases/tag/v0.2.4.1

**Comment by logykk** [comment]
Sorry about that, I checked again and you were right it was one off. The patch is live and will be fixed the next build.

**Comment by metalphoenix** [comment]
Dude, thanks. Hope that fixes the "can't download anything but the first playlist" issue too.
Rock on!
