### ISSUE TITLE
Download location incorrect (relative to zspotify root)

### ISSUE THREAD

**Issue by ggdorman** [Footsiefat/zspotify#196]
**Describe the bug**
It does not appear to be possible to set the root download location to a path outside the zspotify folder.

**To Reproduce**
Songs will always download to the set destination _inside_ the zsoptify folder. Eg. `"ROOT_PATH": "~/Music/ZSpotify/"` will actually download to` zspotify/~/Music/ZSpotify/`. This may be a syntax error on my part, so feel free to let me know.

**Comment by Mikescher** [comment]
I don't think you can use `~` to get the home folder in the config. You have to fully specify it à `/home/user/Music/ZSpotify`

**Comment by ggdorman** [comment]
Could this functionality please be added, it would be very useful! Thank you.

**Comment by ggdorman** [comment]
I will close this bug report and create a feature request.
