### ISSUE TITLE
Usage of Librespot puts their project at risk

### ISSUE THREAD

**Issue by stephanlensky** [Footsiefat/zspotify#197]
Hi,

I'm a user of Librespot for my own (unpublished) Spotify projects, and I think it is really amazing what their team has been able to accomplish with regards to reverse engineering the Spotify client. As I understand it, many rely on the project to support playback on devices without official Spotify clients.

However, (public) projects like this put that all in jeopardy, and it is only a matter of time once this gets popular before Spotify directs their attention towards Librespot. Once that happens, Librespot itself will be taken down, development on it will stop, and this project will stop functioning the moment Spotify changes their API slightly. It doesn't matter that you've mirrored this repository, as if your dependency on Librespot gets taken down there will be no way for your application to function.

For obvious reasons, publishing piracy tools like this is in clear violation of the wishes of the Librespot developers, and they state as much very clearly all over their code (which they have offered for you to use free of charge).

In my opinion, it is amazing enough that Librespot exists at all, and it is simple enough for anyone to write a tool using it to download songs for their own personal use. Publishing and publicizing something like this though is sure to attract negative attention, and you are affecting a huge number of people beyond just yourself if Spotify decides to pursue action against Librespot. Not to mention the fact that your own application will also stop working in this case.

Do you have any thoughts on this? IMO, you should remove your dependency on Librespot, so you are not putting them at risk.

Thanks for reading.

**Comment by logykk** [comment]
I know I addressed this in the Discord server earlier but for anyone else reading this with similar concerns:

ZSpotify is to tightly integrated into librespot. To simply remove it as a dependency would require a colossal rewrite of ZSpotify that we don't have the spare time to accomplish in the foreseeable future. We are a public project for good reason, there is a clear need for a program like this to exist. It is unrealistic to expect the majority of our users to write their own tool for personal use. The accessibility of our tool to as many users as possible is currently our biggest focus. 

While I acknowledge all of your points surrounding Spotify causing the project to cease functioning with one API change that same argument is true for any other project of that nature including our own should we ever have to make one. No matter how Spotify try to put a stop to projects like librespot, whether that be by slightly changing their API or by taking direct legal action, it will end in a cat and mouse scenario with developers are constantly forking, changing, and rewriting their libraries to keep up with Spotify.

In the case of a Spotify downloader going against the wishes of the librespot developers, they have not said anything to or about us regarding the use of their library in ZSpotify and have actually helped us many times in regards to issues we've been having with their library - see their [issues section](https://github.com/kokarare1212/librespot-python/issues?q=is%3Aissue+) where at the time of writing 8 out of the 10 latest issues were opened by ZSpotify developers. At the end of the day the librespot guys know what they're doing making such a tool public, if they wish to reach out to us regarding our use of their library we're open to discussion. We're all very thankful that librespot is an open source project and we are able to use it as the core of ZSpotify.

Should anything happen that causes us to be completely unable to continue using upstream librespot as a dependency, we are prepared to fork and maintain our own version specifically for ZSpotify at the cost of significantly slower progress on the main ZSpotify project. This is a last resort as we really do want to keep using librespot.

We love librespot as much as you do and understand your concerns, but the current state of ZSpotify makes it almost impossible to remove librespot anytime soon. If kokarare1212 takes serious issue with what we're doing they're welcome to talk to us.
