### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KhyalKara** [Footsiefat/zspotify#202]
**Describe the bug**
Unable to download any track.

**To Reproduce**
1. Try download any track.

**Additional context**
```
Traceback (most recent call last):
  File "/path/to/zspotify/zspotify/track.py", line 135, in download_track
    total_size = stream.input_stream.size / ""
TypeError: unsupported operand type(s) for /: 'int' and 'str'
```
**Possible Fix**
1. Remove `/ ""` from line 135 of track.py

**Comment by KhyalKara** [comment]
Fixed by @logykk

**Comment by logykk** [comment]
Thanks for the report, I've just fixed it in the latest push. Just a little typo nothing serious.
