### ISSUE TITLE
[FEATURE] New Windows Release

### ISSUE THREAD

**Issue by ryantheleach** [Footsiefat/zspotify#203]
It looks like there's been some significant fixes since the last release, I'd appreciate an updated windows release when you can, <3.

**Comment by logykk** [comment]
There haven't been any Windows releases in a while because we've been working a new installer setup to simplify the setup process and fix all the common bugs that caused by the current setup. I do agree though there's been a lot of progress so I'll try to get a new release out later today.

**Comment by logykk** [comment]
Our new Windows Installer v0.5.2 is out now, hope you enjoy.

**Comment by ryantheleach** [comment]
Thanks!

I ended up getting it working through python, but I still appreciate the release as it makes it accessible to others.
