### ISSUE TITLE
[FEATURE] retieve more music tag metadata

### ISSUE THREAD

**Issue by AuXBoX** [Footsiefat/zspotify#205]
Would be good to retrieve extra metadata like Album Artist & Genre

**Comment by leonbohmann** [comment]
Problem here is, that Spotify does not store Genres in their Track-Metadata. If you query the track and look at the response, there is no Genre-Tag.

What one could do is query the artist of the track and retrieve genres from there..

**Comment by leonbohmann** [comment]
See #218

**Comment by logykk** [comment]
All sorted in #219.
