### ISSUE TITLE
Doesn't seem to detect Premium Family Accounts

### ISSUE THREAD

**Issue by matt1544** [Footsiefat/zspotify#21]
I'm not sure that "check_premium" is correctly detecting family accounts. They are considered Premium accounts, but the python script returns a result of "free account".

I can manually modify the script to force Very High quality:

print("### DETECTED FREE ACCOUNT - USING HIGH QUALITY ###")
QUALITY = AudioQuality.VERY_HIGH

and my resulting MP3s show up us:

Duration: 00:02:52.04, start: 0.025056, bitrate: 324 kb/s
Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s

Happy to help run something if it would help you troubleshoot this, or produce output of the check_premium for my account type.

**Comment by matt1544** [comment]
> Check on the spotify account panel that you are indeed premium

Yes, it says:

Your plan
Spotify Premium Family
Up to 6 separate Premium accounts for people who live together.

Learn more
You’re a member of a Family plan.

**Comment by Footsiefat** [comment]
Is this with a family premium account because thafs what i need to check?

**Comment by matt1544** [comment]
Thanks @nikos9742 

this is what I get. (obviously redacted whatever looked sensitive).

Interesting that I don't see a "product" at all.

{'display_name': 'XXX', 'email': 'XXX', 'external_urls': {'spotify': 'https://open.spotify.com/user/XXX'}, 'followers': {'href': None, 'total': 0}, 'href': 'https://api.spotify.com/v1/users/XXX', 'id': 'XXX', 'images': [], 'policies': {'opt_in_trial_premium_only_market': False}, 'type': 'user', 'uri': 'spotify:user:XXX'}
