### ISSUE TITLE
[BUG] {playlist_num} is not parsed

### ISSUE THREAD

**Issue by rtxbae** [Footsiefat/zspotify#220]
**Describe the bug**
When downloading playlist using `--output="{playlist}/{playlist_num} {song_name}.{ext}"` the "{playlist_num}" is not parsed and final file name will have literal "{playlist_num}" as name.

**To Reproduce**
1. Enter `python zspotify https://open.spotify.com/playlist/1yZ1uJo1g8UQTPLyHx8aMC?si=e2e2ef73252c4597 --output="{playlist}/{playlist_num} {song_name}.{ext}`
2. Enter
3. See output file name

**Expected behavior**
File name named properly.

**Screenshots**

**System Info:**
 - OS: [e.g. Windows 11, Ubuntu 20.04] Windows 10
 - Release: [e.g. exe, docker, source] source 
 - Version (If using a binary release)

**Additional context**

**Comment by logykk** [comment]
It seems #195 fixed this properly.
