### ISSUE TITLE
[BUG] cant download anything

### ISSUE THREAD

**Issue by thaynos** [Footsiefat/zspotify#230]
**Describe the bug**
i downloaded the repo and tried to run the zspotify.py but it doesn't give any output whatsoever

**Expected behavior**
for it to show an error output at the very least

**Screenshots**
![image](https://user-images.githubusercontent.com/83282129/146161820-93c8393b-acf6-42e6-9df0-bd29a7305108.png)

**System Info:**
 - OS: Windows 10
 - Release: source

**Additional context**
if i use the main.py it works fine

**Comment by logykk** [comment]
zspotify.py won't do anything when run directly, you have to run either `zspotify` (the folder), or `zspotify/__main__.py`
