### ISSUE TITLE
Feature request: Genre data from Spotify

### ISSUE THREAD

**Issue by jaredwooden** [Footsiefat/zspotify#29]
It would be amazing if this tool could pull in genre data (which I believe sits at the album level in the Spotify API) to each of the downloaded tracks. Awesome work on this by the way!!

**Comment by vicelversa** [comment]
Second this. The genre data _may_ live at either Track / Album / Artist level and can sometimes not exist at one or more of those levels. For tracks with multiple genre data, append each unique genre to the files tag info separated by a comma.
