### ISSUE TITLE
Part of audio keeps skipping in some tracks.

### ISSUE THREAD

**Issue by stmeehee** [Footsiefat/zspotify#35]
Some track downloaded will have missing few seconds of audio somewhere, only checked files converted to ogg format.
Tried replicating the issue with same song that was skipping using ogg and raw formats but failed.

**Comment by MKetonen** [comment]
Have the same issue. Thought mp3 files were OK, but after listening some of the files skip at some point. Those files are missing a second or two. This seem to happen both
byte = stream.input_stream.stream().read(-1)
and
byte = stream.input_stream.stream().read(1024 * 128)

Using Windows 10 and Spotify free account.

**Comment by Footsiefat** [comment]
Hey guys if you can provide a URL where this issue happens, that would be appreciated otherwise I wont be able to debug and fix this issue.
