### ISSUE TITLE
Some songs fail conversion

### ISSUE THREAD

**Issue by bigchipbag** [Footsiefat/zspotify#4]
I'm trying to determine the source of this issue and if it is client side - but this is happening with all playlists I try to download. I need to redirect stdout to a file to capture the source of the problem since it fills the terminal.

```
[vorbis @ 0x5639b52982c0] Data packet before valid headers
Error while decoding stream #0:0: Invalid data found when processing input
size=    6977kB time=00:00:20.01 bitrate=2855.2kbits/s speed=74.9x    
video:0kB audio:6977kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001428%
Conversion failed!
```

**Comment by bigchipbag** [comment]
Seems most likely client-side since re-running the same command often continues beyond where it stopped.

**Comment by bigchipbag** [comment]
This could be client side when running more than one instance at a time.

**Comment by Footsiefat** [comment]
![image](https://user-images.githubusercontent.com/12180913/137581106-5aafd585-445b-45fd-977c-6d3653a1e847.png)
yeah I couldnt replicate the issue on windows but I added a try/except
