### ISSUE TITLE
Tracks are cut off at the end

### ISSUE THREAD

**Issue by bigchipbag** [Footsiefat/zspotify#8]
Many tracks are cut off at the end or only partially downloaded.

Examples to follow but I think Kids in America, the Chicago Bulls theme, many more from my downloads today.

**Comment by Footsiefat** [comment]
think I might know what the issue is 
```
byte = stream.input_stream.stream().read()
if byte == b'':
    break
```
basically the guy who made the library messed up the detection for when the song ends so I had to add a makeshift detector but it may be activating before the song actually ends.

Ill have a look into solving this issue later

**Comment by bigchipbag** [comment]
For all the tracks I have checked there are no issues at the end. 
The only detectable one is still the Chicago Bulls theme from the alan parsons project. It sounds like the final audio in the track is corrupted.
